spring.application.name=demoThymleaf

# Server
server.port=8078

# Thymeleaf
spring.thymeleaf.cache=false

# Đa ngôn ngữ (i18n)
spring.messages.basename=i18n/messages
spring.web.locale=vi_VN

# Kết nối SQL Server
spring.datasource.url=jdbc:sqlserver://LEVUHAI:1433;databaseName=WEBBT7;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
